### ISSUE TITLE
Does CCSDS MO create/extract header/contents?

### ISSUE THREAD

**Issue by ghost** [esa/CCSDS_MO#1]
Does MO or MAL API unmarshal the CCSDS header or data contents for inspection, e.g. validate the sender of origin, validate the schema if it is compliant with CCSDS format before the data transport (send)?

I'm looking for API or library that creates/extracts CCSDS message format, which can be used in building and customizing a telemetry simulator. would appreciate any pointer? 

thanks

**Comment by CesarCoelho** [comment]
Could you give us a bit more of detail?
What do you mean with "CCSDS Header"? Are you talking about the Space Packet Protocol (SPP) primary header or something else?
With "CCSDS format" do you mean SPP format?

Do you intend to use MO services for your telemetry simulator? If so, you should look at the Parameter service that is available in the Monitor and Control (M&C) services set. I have done something similar before, please check the following link and go through the guide, I believe that it will help you:
https://github.com/esa/CCSDS_MO/wiki/CCSDS-Mission-Operations-services-for-Newbies
